services:
  kotai-app:
    build: .
    container_name: kotai_nextjs
    restart: unless-stopped
    ports:
      - "3002:3002"
    volumes:
      - ./data:/app/data
      - ./db:/app/db
    environment:
      - PORT=3002
