CREATE TABLE IF NOT EXISTS admins (
  id INTEGER PRIMARY KEY,
  google_id TEXT UNIQUE NOT NULL,
  email TEXT NOT NULL,
  name TEXT,
  avatar TEXT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS price_cache (
  id INTEGER PRIMARY KEY CHECK (id = 1),
  price_usd REAL,
  price_brl REAL,
  change_24h REAL,
  volume_24h REAL,
  market_cap REAL,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS news_cache (
  id INTEGER PRIMARY KEY CHECK (id = 1),
  summary TEXT,
  generated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS visits (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  page TEXT NOT NULL,
  ip TEXT,
  visited_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
